name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点执行
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fork Sync
        uses: tgymnich/fork-sync@v2.0.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: openclaw # fork 的上游仓库 user
          head: main # fork 的上游仓库 branch
          base: main # 本地仓库 branch
