name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点执行
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-chechout: |
            /*
            !/.github
          sparse-checkout-cone-mode: false

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/openclaw/openclaw.git
          git fetch upstream

      - name: Push 
        run: |
          git rebase upstream/main
          git push origin main --force-with-lease
